services:
  db:
    container_name: postgres_fdb_container
    image: postgres:17.0
    restart: always
    volumes:
      - pgdata_sovareq:/var/lib/postgresql/data
    env_file:
      - ~/data/.env

  bot:
    ports:
        - 5000:5000
    container_name: fdb_bot_container
    build:
      context: .
    restart: always
    volumes:
      - ~/data:/Feedback-Bot/data
    env_file:
      - ~/data/.env
    depends_on:
      - db

volumes:
  pgdata_sovareq:
